# aceita apenas links para o Reddit
type: submission
priority: 1
moderators_exempt: true
comment: A sua postagem foi removida porque não contém um link direto para um subreddit. Leia [as regras do sub](https://www.reddit.com/r/EmPortugues/wiki/rules) e siga o padrão adotado pelas demais postagens para ter sua postagem aceita da próxima vez.
comment_stickied: true
modmail: |
    {{title}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar postagem sem link para sub

~domain: reddit.com

action: spam
action_reason: sem link para sub
set_flair:
    template_id: b9003d0a-3999-11e9-9008-0eabe0609938
overwrite_flair: true

---

# remove links para a versão antiga do Reddit
type: submission
priority: 1
moderators_exempt: true
comment: A sua postagem foi removida porque contém um link para a versão antiga do Reddit (old.reddit.com). Leia [as regras do sub](https://www.reddit.com/r/EmPortugues/wiki/rules) e siga o padrão adotado pelas demais postagens para ter sua postagem aceita da próxima vez.
comment_stickied: true
modmail: |
    {{title}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar postagem com link para a versão antiga

domain: old.reddit.com

action: remove
action_reason: link para a versão antiga
set_flair:
    template_id: b9003d0a-3999-11e9-9008-0eabe0609938
overwrite_flair: true

---

# remove links HTTP
type: link submission
priority: 1
moderators_exempt: true
comment: A sua postagem foi removida porque o link direciona a um endereço HTTP. Leia [as regras do sub](https://www.reddit.com/r/EmPortugues/wiki/rules) e siga o padrão adotado pelas demais postagens para ter sua postagem aceita da próxima vez.
modmail: |
    {{title}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar postagem com link HTTP

~domain (includes): https://

action: spam
action_reason: link HTTP
set_flair:
    template_id: b9003d0a-3999-11e9-9008-0eabe0609938
overwrite_flair: true

---

# remove links com parâmetros UTM
type: link submission
priority: 1
moderators_exempt: true
comment: A sua postagem foi removida porque o link contém parâmetro UTM. Leia [as regras do sub](https://www.reddit.com/r/EmPortugues/wiki/rules) e siga o padrão adotado pelas demais postagens para ter sua postagem aceita da próxima vez.
comment_stickied: true
modmail: |
    {{title}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar postagem com link com parâmetro UTM

domain (regex): \?

action: spam
action_reason: link com parâmetro UTM
set_flair:
    template_id: b9003d0a-3999-11e9-9008-0eabe0609938
overwrite_flair: true

---

# remove postagens textuais
type: text submission
priority: 1
moderators_exempt: true
comment: A sua postagem foi removida porque postagens textuais não são permitidas neste sub. Leia [as regras do sub](https://www.reddit.com/r/EmPortugues/wiki/rules) e siga o padrão adotado pelas demais postagens para ter sua postagem aceita da próxima vez.
comment_stickied: true
modmail: |
    {{title}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar postagem textual

action: remove
action_reason: postagem textual
set_flair:
    template_id: b9003d0a-3999-11e9-9008-0eabe0609938
overwrite_flair: true

---

# remove postagens cruzadas
type: crosspost submission
priority: 1
moderators_exempt: true
comment: A sua postagem foi removida porque postagens cruzadas não são permitidas neste sub. Leia [as regras do sub](https://www.reddit.com/r/EmPortugues/wiki/rules) e siga o padrão adotado pelas demais postagens para ter sua postagem aceita da próxima vez.
comment_stickied: true
modmail: |
    {{title}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar postagem cruzada

action: remove
action_reason: postagem cruzada
set_flair:
    template_id: b9003d0a-3999-11e9-9008-0eabe0609938
overwrite_flair: true

---

# remove links para diversas fontes
type: any
priority: 1
moderators_exempt: true
comment: A sua postagem foi removida porque o link que você compartilhou não é permitido neste sub. Leia [as regras do sub](https://www.reddit.com/r/EmPortugues/wiki/rules) e siga o padrão adotado pelas demais postagens para ter sua postagem aceita da próxima vez.
comment_stickied: true
modmail: |
    {{title}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar postagem com link externo

domain+body: [v.redd.it, youtube.com, youtu.be, vimeo.com, streamable.com, instagram.com, imgur.com, flickr.com, scribd.com, medium.com, github.com, gitlab.com, facebook.com, twitter.com, tumblr.com, wordpress.com, blogspot.com]

action: spam
action_reason: link externo
set_flair:
    template_id: b9003d0a-3999-11e9-9008-0eabe0609938
overwrite_flair: true

---

# remove postagens com títulos que não comecem com nome de um subreddit
type: link submission
priority: 2
moderators_exempt: true
comment: A sua postagem foi removida porque não segue o padrão de intitulação de postagens adotado neste sub. Leia [as regras do sub](https://www.reddit.com/r/EmPortugues/wiki/rules) e siga o padrão adotado pelas demais postagens para ter sua postagem aceita da próxima vez.
comment_stickied: true
modmail: |
    {{title}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar postagem com título inadequado

~title (starts-with): r/

action: remove
action_reason: título inadequado
set_flair:
    template_id: b9003d0a-3999-11e9-9008-0eabe0609938
overwrite_flair: true

---

# indica repostagens
type: comment
priority: 3
moderators_exempt: false
comment: Bom bô.
modmail: |
    {{body}} por u/{{author}} em {{subreddit}}: {{permalink}}
modmail_subject: Avaliar repostagem

author:
    is_moderator: true

body: "REEEEEEE"

---
